### ISSUE TITLE
Strange graph layout

### ISSUE THREAD

**Issue by joetsui1994** [kraemer-lab/GRAPEVNE#121]
Occasionally, links connecting a module to two different modules would cross when applying "ARRANGE GRAPH" (see below).

<img width="268" alt="Screenshot 2023-09-26 at 00 13 01" src="https://github.com/kraemer-lab/GRAPEVNE/assets/34651685/b6dbde19-6636-465f-892d-ca696b20e11e">

**Comment by joetsui1994** [comment]
Is it worth looking into [react-flow](https://reactflow.dev/)?

**Comment by jsbrittain** [comment]
For info - we're using [react-diagrams](https://github.com/projectstorm/react-diagrams) at the moment for the graph-based elements, and [Dagre](https://github.com/dagrejs/dagre) for the auto-arrange feature (some tweaking in the code may be able to improve the layouts here). Moving to react-flow library (which is available under the MIT license) is possible (though non-trivial!), and they do operate a subscription-based model around the core library meaning most of the more helpful examples would be restricted.

**Comment by jsbrittain** [comment]
Experimental react-flow build: https://github.com/jsbrittain/GRAPEVNE/tree/react-flow
