### ISSUE TITLE
Template new modules in GRAPEVNE

### ISSUE THREAD

**Issue by jtmccr1** [kraemer-lab/GRAPEVNE#160]
**Is your feature request related to a problem? Please describe.**
It's not a huge inconvenience, but right now there are a few manual steps needed to create a module. And this breaks up the processes of designing a new workflow. What if there is a simple module you'd like to add and don't realize it until you're already making a workflow.

**Describe the solution you'd like**
I would like it to be possible to click a 'new module' button that opens a similar panel to what is shown when you click on a module - however with the option to add input/output/parameters command etc. We'd also want to provide documentation and dependancies. GRAPEVNE could then generate the directory structure and snakemake rule for the module when it inserts it in the graph.

Potentially this module could be 'published' to a github repo as a pull request. 

**Describe alternatives you've considered**
Doing it by hand.

**Additional context**
Not solving a huge problem here, but it would make the software more accessible to those without much experience in snakemake.

**Comment by jsbrittain** [comment]
Mockup templating screen:

![Image](https://github.com/kraemer-lab/GRAPEVNE/assets/98161205/46f50513-541a-4db8-a0ad-d2626cf42133)



![Image](https://github.com/kraemer-lab/GRAPEVNE/assets/98161205/bb00a9d1-c434-4afd-aa77-092fc6d07e3c)


![Image](https://github.com/kraemer-lab/GRAPEVNE/assets/98161205/f9f31bb1-8d3b-432a-80f2-6806c4d77d85)

The 'parameters' section has been left deliberately generic at this time, but there is substantial scope for more fine-grained decomposition of parameter / parameters types / and incorporation of params lists automatically into the docstring.
