### ISSUE TITLE
Provide grapenve(-py) helper scripts

### ISSUE THREAD

**Issue by jsbrittain** [kraemer-lab/GRAPEVNE#349]
Provide helper scripts for use in grapevne modules. These will be imported in the module Snakefiles and used to redirect input/output filename, etc. This will 1) dramatically simplify the Snakefile construction process by handling input/output namespace redirection automaticall (with the use of simplified wrappers), and 2) provide a level of abstraction that can be used to automate Snakemake 7 and 8 support.

For example, existing rules require something like this:
```python
indir = config["input_namespace"]
params = config["params"]
infile = params["Filename"]

rule demo:
    input:
        infile = f"results/{indir}/{infile}"
    ...
```

This would be replaced with wrapper scripts (`input` and `params` in this case), abstracting away the namespace connections and permitting e.g. remote file access to be used depending on context and Snakemake version:
```
rule demo:
    input:
        infile = input(params("Filename"))
```

Since these wrapper would be required in the Snakefie (outside of any conda environment), they would need to be installed and available on the host system. To facilitate this we propose bundling each workflow with a `grapevne_helper.py` script that checks for, installs the most recent `grapevne` package and exposes its namespace to the Snakefile (this can be done in several ways).

This greatly simplifies the users' exposure to namespace mapping, reducing the risk of error, and permits #189, #146

**Comment by jsbrittain** [comment]
The grapevne wrapper system is available here: https://github.com/kraemer-lab/grapevne-py
Published on PyPI here: https://pypi.org/project/grapevne/

Tests are available in the wrapper respository, with specific attention drawn to the workflow examples: https://github.com/kraemer-lab/grapevne-py/tree/main/tests/test-repo/workflows

Each modules comes with a `workflow/grapevne_helper.py` script that can be used to install the `grapevne` package from PyPI and expose its functionality in the Snakefile (this can be done as named imports [as below], as a context manager, or references to a Helper object instance).

As a usage example, a simple `copy` module might be implemented like this:
```
"""Copy file from one directory to another.

This version demonstrates use of the helper by importing function names ('script', 'resource', etc. into the namespace)
"""
configfile: "config/config.yaml"

from grapevne_helper import *
import shutil

init(workflow, config)

rule copy:
    input:
        filename=input(params("filename")),
        dummy_script=script("dummy.sh"),
        dummy_resource=resource("dummy.txt"),
    output:
        filename=output(params("filename")),
    log:
        log("copy.log"),
    run:
        shutil.copy(input.filename, output.filename)
```

**Comment by jsbrittain** [comment]
@joetsui1994 @abhidg Comments welcome on the above proposal. I have a working version but will need to modify existing modules for compatilbility and rework the central documentation, so would welcome any comments before I embark on that. A side-benefit of providing this functionality is that we can provide updates through the `grapevne` (PyPI) package itself from now on.

**Comment by joetsui1994** [comment]
This makes sense and looks useful. My only (and perhaps unfounded) concern is whether this would present an additional barrier to people who already has some experience with Snakemake and is starting to work with GRAPEVNE?

**Comment by abhidg** [comment]
Looks good @jsbrittain! Do we want to be able to specify the grapevne-py version when installing? If backwards compat is guaranteed, then not an issue.

**Comment by jsbrittain** [comment]
@joetsui1994 @abhidg - thanks for comments!

With regards snakemake familiarity, it's a slightly different way of thinking for us (who have developed grapevne modules already), but having converted a few I can already see how much cleaner/simpler it makes the snakefiles. At present, writing grapevne modules you need to know 1) how to use snakemake, and 2) recognise the intricacies of grapevne (i.e. they need to know and remember that all results are expected to go into a 'results/{indir}' folder, and that indir comes from config['input_namespace']). With the proposed approach we deal with all of that behind the scenes. And, of course, we don't expect every user to interact directly with the snakefiles themselves, but for those that do it provides a coherent framework, rather than a set of arbitrary rules.

With regards versioning, I wasn't entirely sure what the best approach was here or where the user should specify it. The fact that we need grapevne-py installed in the base environment means we can't simply add it as a conda dependency, which is why the helper function exists. I could extend the `init` function with an optional `version=1` parameter so that it is controllable in the Snakefile (i.e. user would specify `init(workflow, version=1)`, and then only import grapevne at the `init` stage (presumably with a special case to install v0 if v1 is not found). Does that sound more reasonable?

**Comment by abhidg** [comment]
> With regards versioning, I wasn't entirely sure what the best approach was here or where the user should specify it. The fact that we need grapevne-py installed in the base environment means we can't simply add it as a conda dependency, which is why the helper function exists. I could extend the `init` function with an optional `version=1` parameter so that it is controllable in the Snakefile (i.e. user would specify `init(workflow, version=1)`, and then only import grapevne at the `init` stage (presumably with a special case to install v0 if v1 is not found). Does that sound more reasonable?

That sounds good!

**Comment by jsbrittain** [comment]
Closing as complete. Further refinements can be considered on the grapevne-py repo: https://github.com/kraemer-lab/grapevne-py.
