### ISSUE TITLE
Unable to find builderjs/dist/index.js

### ISSUE THREAD

**Issue by joetsui1994** [kraemer-lab/GRAPEVNE#43]
I got the error that says the electron app is unable to find the module '/PhyloFlow.app/Contents/Resources/app/node_modules/builderjs/dist/index.js' after it launches. This seems to have to do with line 39 in electron-app/package.json. Changing it from "builderjs": "file:../builderjs" to "builderjs": "file:../builderjs/dist/src" seems to get rid of the error.

**Comment by jsbrittain** [comment]
Bug confirmed on a clean build.
Also `js-yaml` is missing as a build dependency.
